# link our services

version: "3.7"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment: #set env variables here
      - APP_NAME=MyFlaskApp
    expose: #only expose ports to other containers on the same network
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"